language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 0ae2d96ae0e3a8cea17125c1214cf9211c3bf9bc6762426499823e8ae8e74460
  # - COVERALLS_REPO_TOKEN=$repo_token npm run coveralls
# "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
